config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path_prefix => 'd', :skip => [:registrations] 
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
  resources :stages
  resources :prospects
  resources :roles
  resources :users
  resources :dashboard

  root 'dashboard#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.nil?
        can :read, :all
    elsif user.role?("salesManager")
        can :manage, :all
    elsif user.role?("salesAssociate")
        can :read, :all
        can :create, Prospect
        can :update, Prospect do |prospect|
            prospect.managed_by == user.id
        end
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/customer.rb
class Customer < ActiveRecord::Base

	belongs_to :user, foreign_key: :managed_by
	after_create :empty_prospects

	def empty_prospects
		# binding.pry
		user = self.user
		# binding.pry
		# Prospect.delete(user.prospects.pluck(:id))
		user.prospects.each do |prospect|
			if prospect.full_name == self.full_name
				prospect.delete
			end
			# break
		end
	end
end

app/models/prospect.rb
class Prospect < ActiveRecord::Base
	belongs_to :stage
	belongs_to :user, foreign_key: :managed_by
	validates_presence_of :full_name, :email, :mobile, :location
	validates_uniqueness_of :mobile, :email
	before_create :stage_save
	before_save :stage_check

	def stage_save
		stage = Stage.find_by(name: "New Opportunity").id
		self.stage_id = stage
	end

	def stage_check
		# new_opportunity = Stage.find_by(name: "New Opportunity").id
		won = Stage.find_by(name: "Won").id
		# if self.stage_id == new_opportunity
		# 	binding.pry
		# 	self.save
		if self.stage_id == won
			# user = self.user
			# binding.pry
			# user.prospects.each do |prospect|
				customer = Customer.new
				customer.full_name = self.full_name
				customer.email = self.email
				customer.mobile = self.mobile
				customer.location = self.location
				customer.managed_by = self.managed_by
				# binding.pry
				customer.save
			# end
		end
	end
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_many :users
	validates_presence_of :name
end

app/models/stage.rb
class Stage < ActiveRecord::Base
	has_many :prospects
	validates_presence_of :name, :description, :interest_level
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :role
  has_many :prospects, foreign_key: :managed_by
  has_many :customers, foreign_key: :managed_by
  validates_presence_of :full_name, :mobile
  validates_uniqueness_of :full_name, :email
  before_create :save_as_associate

  def save_as_associate
  	role = Role.find_by(name: "salesAssociate").id
  	self.role_id = role
  end

  def role?(role)
    self.role.name.include? role
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from CanCan::AccessDenied do 
  	redirect_to root_path, notice: "Page not found"
  end
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:full_name, :mobile, :role_id])
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	before_action :authenticate_user!
	def index
		@customers = Customer.all
	end
end

app/controllers/prospects_controller.rb
class ProspectsController < ApplicationController
	before_action :authenticate_user!
	load_and_authorize_resource
	before_action :set_prospect, only: [:edit, :update, :show, :destroy]
	def index
		@prospects = current_user.prospects
		@prospect = Prospect.new
	end

	def new
		@prospect = Prospect.new
	end

	def create
		@prospect = Prospect.new(prospect_params)
		@prospect.managed_by = current_user.id
		respond_to do |format|
			if @prospect.save
				format.html{ redirect_to prospects_path, notice: "Successfully created the Prospect" }
				format.js
			else
				format.html{render :new}
				format.js
			end
		end
	end

	def edit
		
	end

	def update
		if @prospect.update_attributes(prospect_params)
			redirect_to prospects_path
		else
			render action: "edit"
		end
	end

	def show
		
	end

	def destroy
		@prospect.destroy
		redirect_to prospects_path
	end

	private

	def set_prospect
		@prospect = Prospect.find(params[:id])
	end

	def prospect_params
		params.require(:prospect).permit(:full_name, :email, :mobile, :location, :stage_id, :managed_by)
	end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
	before_action :authenticate_user!
	load_and_authorize_resource

	# def index
	# 	@roles = Role.all
	# end

	# def new
	# 	@role = Role.new
	# end

	# def create
	# 	@role = Role.new(role_params)
	# 	if @role.save
	# 		redirect_to roles_path, notice: "Successfully created the role"
	# 	else
	# 		render action: "new"
	# 	end
	# end
end

app/controllers/stages_controller.rb
class StagesController < ApplicationController
	before_action :authenticate_user!
	load_and_authorize_resource
	before_action :set_stage, only: [:edit, :show, :update, :destroy]
	def index
		@stages = Stage.all
		@stage = Stage.new
	end

	def new
		@stage = Stage.new
	end

	def create
		@stage = Stage.new(stage_params)
		if @stage.save
			redirect_to stages_path, notice: "Successfully created the Stage"
		else
			render action: "new"
		end
	end

	def edit
		
	end

	def update
		if @stage.update_attributes(stage_params)
			redirect_to @stage, notice: "Successfully updated the Stage"
		else
			render action: "edit"
		end
	end

	def show
		
	end

	def destroy
		@stage.destroy
		redirect_to stages_path, notice: "Successfully deleted the Stage"
	end

	private

	def set_stage
		@stage = Stage.find(params[:id])
	end

	def stage_params
		params.require(:stage).permit(:name, :description, :interest_level)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :set_user, only: [:edit, :update, :show, :destroy]
	before_action :authenticate_user!
	def index
		@users = User.order('created_at DESC')
		@user = User.new
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		respond_to do |format|
			if @user.save
				format.html {redirect_to users_path, notice: "Successfully created the User"}
				format.js
			else
				format.html{render :new}
				format.js
			end
		end
	end

	def edit
		
	end

	def update
		if @user.update_attributes(user_params)
			redirect_to @user
		else
			render action: "edit"
		end
	end

	def show
		
	end

	def destroy
		@user.destroy
		redirect_to users_path
	end

	private

	def set_user
		@user = User.find(params[:id])
	end

	def user_params
		params.require(:user).permit(:full_name, :email, :password, :password_confirmation, :mobile, :role_id)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/prospects_helper.rb
module ProspectsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/stages_helper.rb
module StagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/index.html.erb
<h2>Listing Customers</h2>

<% if @customers.empty? %>
	<p>No Customers Found</p>
<% else %>
	<table class="table" id="listCustomers">
		<thead>
			<th>Full Name</th>
			<th>Email</th>
			<th>Mobile</th>
			<th>Location</th>
			<th>User</th>
		</thead>
		<tbody>
			<% @customers.each do |customer| %>
				<tr>
					<td><%= customer.full_name %></td>
					<td><%= customer.email %></td>
					<td><%= customer.mobile %></td>
					<td><%= customer.location %></td>
					<td><%= customer.user.full_name %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
<% end %>

<script>
	$(document).ready(function(){
    	$('#listCustomers').DataTable();
	});
</script>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Lead2Sale</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!-- <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li> -->
        <% if user_signed_in? %>
          <li><%= link_to "Prospects", prospects_path %></li>
          <li><%= link_to "Stages", stages_path %></li>
          <li><%#= link_to "Users", users_path %></li>
          <li><%= link_to "Customers", dashboard_index_path %></li>
          <% if current_user.role?("salesManager") %>
            <li><%= link_to "Users", users_path %></li>
          <% end %>
        <% end %>
      </ul>
      <% if notice %> 
        <ul class="nav navbar-nav " style="margin-top:15px">
          <li>
            <b><%= notice %></b>  
          </li>
        </ul>
      <%end%>

      <% if alert %> 
        <ul class="nav navbar-nav " style="margin-top:15px">
          <li>
            <b><%= alert %></b>         
          </li>
        </ul>
      <%end%>
      <!-- <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li>
            <%= link_to current_user.full_name.capitalize, edit_user_registration_path %>
          </li>
          <li>
            <%= link_to "Logout", destroy_user_session_path, method: :delete %>
          </li>
        <% else %>
          <%= link_to "Login", new_user_session_path %>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lead2Management</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
	
	<link rel="stylesheet" href="//cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
	<script src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
	<%= render './layouts/nav' %>
	<!-- <p>
		<%# if user_signed_in? %>
			<%#= current_user.email %> |
			<%#= link_to "Edit Account", edit_user_registration_path %> |
			<%#= link_to "Logout", destroy_user_session_path, method: :delete %>
			<p>
				<%#= link_to "Prospects", prospects_path %> | <%#= link_to "Stages", stages_path %> | <%#= link_to "Users", users_path %> | <%#= link_to "Customers", dashboard_index_path %>
			</p>
		<%# else %>
			<%#= link_to "Login", new_user_session_path %>
		<%# end %>
	</p> -->


	<%= yield %>
</div>

</body>
</html>

app/views/prospects/_errors.html.erb
<div class="alert alert-danger">
	<% if @prospect.errors.any? %>
		<h3>These errors prohibitted the form from being saved : </h3>
		<% @prospect.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	<% end %>
</div>

app/views/prospects/_form.html.erb
<%= form_for(@prospect, remote: true) do |f| %>

	<div class="form-group">
		<label>Full Name : </label><br/>
		<%= f.text_field :full_name, autofocus: true, class: "form-control" %> <br/>
		<span id="fullNameError"></span>
	</div>

	<div class="form-group">
		<label>Email : </label> <br/>
		<%= f.email_field :email, class: "form-control" %> <br/>
		<span id="emailError"></span>
	</div>

	<div class="form-group">
		<label>Mobile : </label> <br/>
		<%= f.text_field :mobile, class: "form-control" %> <br/>
		<span id="mobileError"></span>
	</div>

	<div class="form-group">
		<label>Location : </label> <br/>
		<%= f.text_field :location, class: "form-control" %> <br/>
		<span id="locationError"></span>
	</div>

	<!-- <div class="form-group">
		<label>Stage : </label> <br/>
		<%#= f.collection_select :stage_id, Stage.all, :id, :name, prompt: "Select Stage", class: "form-control" %> <br/>
	</div> -->

	<%= f.submit %> or <%= link_to "Back", prospects_path %>
<% end %>

<script>
  var alphabetFormatter = /^[A-Za-z]+$/;
  var emailFormatter = /^([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5})$/;
  var mobileFormatter = /^[0-9]+$/;

  var formHandle = document.getElementById('new_prospect');
  var fullNameHandle = document.getElementById('prospect_full_name');
  var emailHandle = document.getElementById('prospect_email');
  var mobileHandle = document.getElementById('prospect_mobile');
  var locationHandle = document.getElementById('prospect_location');

  var fullNameErrorHandle = document.getElementById('fullNameError');
  var emailErrorHandle = document.getElementById('emailError');
  var mobileErrorHandle = document.getElementById('mobileError');
  var locationErrorHandle = document.getElementById('locationError');
  
  validate = {
    "full_name": false,
    "email": false,
    "mobile": false,
    "location": false
  }

  function validateFullName(){
    if (fullNameHandle.value == "") {
      fullNameErrorHandle.innerHTML = "Can't be blank";
      validate.full_name = false;
    } else if (!alphabetFormatter.test(fullNameHandle.value)) {
      fullNameErrorHandle.innerHTML = "Should be a valid format";
      validate.full_name = false;
    }else {
      validate.full_name = true;
    }
  }

  function validateEmail(){
    if (emailHandle.value == "") {
      emailErrorHandle.innerHTML = "Can't be blank";
      validate.email = false;
    } else if (!emailFormatter.test(emailHandle.value)) {
      emailErrorHandle.innerHTML = "Should be a valid format";
      validate.email = false;
    }else {
      validate.email = true;
    }
  }

  function validateMobile() {
    if (mobileHandle.value == "") {
      mobileErrorHandle.innerHTML = "Can't be blank";
      validate.mobile = false;
    }else if (!mobileFormatter.test(mobileHandle.value)) {
      mobileErrorHandle.innerHTML = "Should be a valid format";
      validate.mobile = false;
    }else {
      validate.mobile = true;
    }
  }

  function validateLocation() {
  	if (locationHandle.value == "") {
  		locationErrorHandle.innerHTML = "Can't be blank";
  		validate.location = false;
  	}else if (!alphabetFormatter.test(locationHandle.value)) {
  		locationErrorHandle.innerHTML = "Should be a valid format";
  		validate.location = false;
  	} else {
  		validate.location = true;
  	}
  }

  formHandle.addEventListener('submit', function(e){

    validateFullName();
    validateMobile();
    validateEmail();
    validateLocation();

    if (Object.values(validate).includes(false)) {
      e.preventDefault();
    }
  }, false);
</script>

app/views/prospects/_prospects.html.erb
<tr>
	<td><%= link_to @prospect.full_name, @prospect %></td>
	<td><%= @prospect.email %></td>
	<td><%= @prospect.mobile %></td>
	<td><%= @prospect.location %></td>
	<td><%= @prospect.stage.name %></td>
	<td><%= @prospect.user.full_name %></td>
</tr>

app/views/prospects/create.js.erb
<% if @prospect.errors.any? %>
	$('#errorMsg').html("<%= escape_javascript render 'errors' %>");
<% else %>
	$('#errorMsg').hide();
	$('#listProspects').append("<%= escape_javascript render 'prospects' %>");
	$('#new_prospect')[0].reset();
<% end %>

app/views/prospects/edit.html.erb
<h2>Edit Prospect</h2>
<%= form_for @prospect do |f| %>
	<% if @prospect.errors.any? %>
		<% @prospect.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	<% end %>

	<div class="form-group">
		<label>Full Name : </label><br/>
		<%= f.text_field :full_name, autofocus: true, class: "form-control" %> <br/>
	</div>

	<div class="form-group">
		<label>Email : </label> <br/>
		<%= f.email_field :email, class: "form-control" %> <br/>
	</div>

	<div class="form-group">
		<label>Mobile : </label> <br/>
		<%= f.text_field :mobile, class: "form-control" %> <br/>
	</div>

	<div class="form-group">
		<label>Location : </label> <br/>
		<%= f.text_field :location, class: "form-control" %> <br/>
	</div>

	<div class="form-group">
		<label>Stage : </label> <br/>
		<%= f.collection_select :stage_id, Stage.all, :id, :name, prompt: "Select Stage", class: "form-control" %> <br/>
	</div>

	<%= f.submit %> or <%= link_to "Back", prospects_path %>
<% end %>

app/views/prospects/index.html.erb
<div class="row">
	<div class="col-md-7">
		<div class="page-header">
			<h2>Listing Prospects</h2>
		</div>
		<% if @prospects.empty? %>
			<p>No Prospects Found</p>
		<% else %>
			<table class="table" id="listProspects">
				<thead>
					<tr>
						<th>Full Name</th>
						<th>Email</th>
						<th>Mobile</th>
						<th>Location</th>
						<th>Stage</th>
						<th>User</th>
					</tr>
				</thead>
				<tbody>
					<% @prospects.each do |prospect| %>
						<tr>
							<td><%= link_to prospect.full_name, prospect %></td>
							<td><%= prospect.email %></td>
							<td><%= prospect.mobile %></td>
							<td><%= prospect.location %></td>
							<td><%= prospect.stage.name %></td>
							<td><%= prospect.user.full_name %></td>
						</tr>
					<% end %>
				</tbody>
			</table>
		<% end %>
	</div>
	<% if can? :create, Prospect.new %>
		<div class="col-md-5">
			<div class="page-header">
				<h2>Add Prospect</h2>
			</div>
			<div id="errorMsg"></div>
			<%= render 'form' %>
		</div>
	<% end %>
</div>

app/views/prospects/new.html.erb
<h2>Add Prospect</h2>

<%= render 'form' %>

app/views/prospects/show.html.erb
<h2><%= @prospect.full_name %></h2>

<p><b>Name : </b><%= @prospect.full_name %></p>
<p><b>Email : </b><%= @prospect.email %></p>
<p><b>Mobile : </b><%= @prospect.mobile %></p>
<p><b>Location : </b><%= @prospect.location %></p>
<p><b>Stage : </b><%= @prospect.stage.name %></p>

<%= link_to "Invite", new_user_invitation_path(prospect_id: @prospect.id) %>
<% if can? :update, @prospect %>
	<%= link_to "Edit", edit_prospect_path(@prospect) %>|
<% end %>
<%= link_to "Destroy", prospect_path(@prospect), method: :delete %>

app/views/stages/_form.html.erb
<%= form_for @stage do |f| %>
	<% if @stage.errors.any? %>
		<% @stage.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	<% end %>

	<div class="form-group">
		<label>Name : </label><br/>
		<%= f.text_field :name, autofocus: true, class: "form-control" %> <br/>
	</div>

	<div class="form-group">
		<label>Description : </label> <br/>
		<%= f.text_area :description, class: "form-control" %> <br/>
	</div>

	<div class="form-group">
		<label>Interest Level : </label> <br/>
		<%= f.collection_radio_buttons :interest_level, (1..5).map{|n| [n, n]}, :first, :last, class: "form-control" %> <br/>
	</div>

	<%= f.submit %> or <%= link_to "Back", stages_path %>
<% end %>

app/views/stages/edit.html.erb
<h2>Edit Stage</h2>

<%= render 'form' %>

app/views/stages/index.html.erb
<div class="row">
	<div class="col-md-7">
		<div class="page-header">
			<h2>Listing Stages</h2>
		</div>
		<% if @stages.empty? %>
			<p>No Stages Found</p>
		<% else %>
			<table class="table">
				<thead>
					<tr>
						<th>Name</th>
						<th>Description</th>
						<th>InterestLevel</th>
					</tr>
				</thead>
				<tbody>
					<% @stages.each do |stage| %>
						<tr>
							<td><%= link_to stage.name, stage %></td>
							<td><%= stage.description %></td>
							<td><%= stage.interest_level %></td>
						</tr>
					<% end %>
				</tbody>
			</table>
		<% end %>
	</div>
	<% if can? :create, Stage.new %>
		<div class="col-md-5">
			<div class="page-header">
				<h2>Add Stage</h2>
			</div>
			<%= render 'form' %>
		</div>
	<% end %>
</div>

app/views/stages/new.html.erb
<h2>Add Stage</h2>

<%= render 'form' %>

app/views/stages/show.html.erb
<h2><%= @stage.name %></h2>

<p><b>Name : </b><%= @stage.name %></p>

<p><b>Description : </b><%= @stage.description %></p>

<p><b>Interest Level : </b><%= @stage.interest_level %></p>

<%= link_to "Edit", edit_stage_path(@stage) %>

<%= link_to "Destroy", stage_path(@stage), method: :delete %>

app/views/users/_errors.html.erb
<div class="alert alert-danger">
	<% if @user.errors.any? %>
		<h3>These errors prohibitted the form from being saved : </h3>
		<% @user.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	<% end %>
</div>

app/views/users/_users.html.erb
<tr>
	<td><%= link_to @user.full_name, @user %></td>
	<td><%= @user.email %></td>
	<td><%= @user.mobile %></td>
	<td><%= @user.role.name %></td>
</tr>

app/views/users/create.js.erb
<% if @user.errors.any? %>
	$('#errorMsg').html("<%= escape_javascript render 'errors' %>");
<% else %>
	$('#errorMsg').hide();
	$('#listUsers').append("<%= escape_javascript render 'users' %>")
	$('#new_user')[0].reset();
<% end %>

app/views/users/edit.html.erb
<h2>Edit User</h2>

<%= render 'form' %>

app/views/users/index.html.erb
<div class="row">
	<div class="col-md-7">
		<div class="page-header">
		<h2>Listing Users</h2>	
		</div>
		<% if @users.empty? %>
			<p>No Users Found</p>
		<% else %>
			<table class="table" id="listUsers">
				<thead>
					<tr>
						<th>Name</th>
						<th>Email</th>
						<th>Mobile</th>
						<th>Role</th>
					</tr>
				</thead>
				<tbody>
					<% @users.each do |user| %>
						<tr>
							<td><%= link_to user.full_name, user %></td>
							<td><%= user.email %></td>
							<td><%= user.mobile %></td>
							<td><%= user.role.name %></td>
						</tr>
					<% end %>
				</tbody>
			</table>
		<% end %>
	</div>
	<% if can? :create, User.new %>
		<div class="col-md-5">
			<div class="page-header">
				<h2>Add User</h2>
			</div>
			<div id="errorMsg"></div>
			<%= render 'form' %>
		</div>
	<% end %>
</div>

<script>

  $(document).ready(function(){
    $('#listUsers').DataTable();
  });
</script>

app/views/users/new.html.erb
<h2>Add User</h2>

<%= render 'form' %>

app/views/users/show.html.erb
<h2><%= @user.full_name %></h2>

<p><b>Name : </b><%= @user.full_name %></p>

<p><b>Email : </b><%= @user.email %></p>

<p><b>Mobile : </b><%= @user.mobile %></p>

<p><b>Role : </b><%= @user.role.name %></p>

<% if can? :update, @user %>
	<%= link_to "Edit", edit_user_path(@user) %>
<% end %>

<% if can? :destroy, @user %>
	<%= link_to "Destroy", user_path(@user), method: :delete %>
<% end %>